# Goal - Ensure the docker files n docker images r security tested.

name: Docker Scans

on:
  workflow_call:


jobs:
    dockerfile-lint-and-scan:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                folders: ['frontend', 'backend']
        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: ${{ matrix.folders }} Dockerfile lint
              uses: hadolint/hadolint-action@v3.1.0
              with:
                  dockerfile: ${{ matrix.folders }}/Dockerfile

