# Goal - Ensure the docker files n docker images r security tested.

name: Docker Scans

on:
  workflow_call:


jobs:
    dockerfile-lint-and-scan:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                folders: ['frontend', 'backend']
        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: ${{ matrix.folders }} Dockerfile lint
              uses: hadolint/hadolint-action@v3.1.0
              with:
                  dockerfile: ${{ matrix.folders }}/Dockerfile


            - name: Docker Setup 
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}


            - name: Docker Build ${{ matrix.folders }} 
              run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/devboard-${{ matrix.folders }}:latest .
              working-directory: ${{ matrix.folders }}

            - name: Run Trivy Scan ${{ matrix.folders }} 
              uses: aquasecurity/trivy-action@v2
              with:
                image-ref: ${{ vars.DOCKERHUB_USERNAME }}/devboard-${{ matrix.folders }}:latest 
                format: 'table'
                exit-code: '1'
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'CRITICAL,HIGH'
